WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), CPR_EVENTS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.PARENT_EVENT_ID,
		CLINICAL_EVENT.EVENT_CD,
		CE_DATE_RESULT.RESULT_DT_TM
	FROM
		CE_DATE_RESULT,
		CLINICAL_EVENT,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 99985 -- Date
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			1149292336, -- CPR D/T Event Recognized
			1149297359 -- CPR Event Ended at
		)
		AND CLINICAL_EVENT.EVENT_ID = CE_DATE_RESULT.EVENT_ID
		AND CE_DATE_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
), CODE_START AS (
	SELECT DISTINCT
		CPR_EVENTS.ENCNTR_ID,
		CPR_EVENTS.PARENT_EVENT_ID,
		--MIN(CPR_EVENTS.EVENT_ID) AS EVENT_ID,
		MIN(CPR_EVENTS.RESULT_DT_TM) AS RESULT_DT_TM
	FROM
		CPR_EVENTS
	WHERE
		CPR_EVENTS.EVENT_CD = 1149292336 -- CPR D/T Event Recognized
	GROUP BY
		CPR_EVENTS.ENCNTR_ID,
		CPR_EVENTS.PARENT_EVENT_ID
), CODE_END AS (
	SELECT DISTINCT
		CPR_EVENTS.PARENT_EVENT_ID,
		--MIN(CPR_EVENTS.EVENT_ID) AS EVENT_ID,
		MAX(CPR_EVENTS.RESULT_DT_TM) AS RESULT_DT_TM
	FROM
		CPR_EVENTS
	WHERE
		CPR_EVENTS.EVENT_CD = 1149297359 -- CPR Event Ended at
	GROUP BY
		CPR_EVENTS.PARENT_EVENT_ID
), CODE_DATES AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		PATIENTS.PERSON_ID,
		PATIENTS.ALIAS,
		CPR_EVENTS.PARENT_EVENT_ID,
		CODE_START.RESULT_DT_TM AS START_DATETIME,
		CODE_END.RESULT_DT_TM AS STOP_DATETIME
	FROM
		CODE_START,
		CODE_END,
		CPR_EVENTS,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CPR_EVENTS.ENCNTR_ID(+)
		AND CPR_EVENTS.PARENT_EVENT_ID = CODE_START.PARENT_EVENT_ID(+)
		AND CPR_EVENTS.PARENT_EVENT_ID = CODE_END.PARENT_EVENT_ID(+)
)

SELECT DISTINCT
	CODE_DATES.ALIAS AS FIN,
	--CODE_DATES.PARENT_EVENT_ID,
	pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS VITAL_DATETIME,
	pi_get_cv_display(EVENT_CD) AS VITAL,
	CLINICAL_EVENT.RESULT_VAL AS VITAL_RESULT,
	pi_get_cv_display(CLINICAL_EVENT.RESULT_UNITS_CD) AS RESULT_UNITS
FROM
	CLINICAL_EVENT,
	CODE_DATES
WHERE
	CODE_DATES.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
	AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
	AND CODE_DATES.PERSON_ID = CLINICAL_EVENT.PERSON_ID
	AND CLINICAL_EVENT.EVENT_CD IN (
		31806, -- Hct
		31854, -- Hgb
		30098, -- Systolic Blood Pressure
		134401648, -- Arterial Systolic BP 1
		30065, -- Peripheral Pulse Rate
		119822527, -- Apical Heart Rate
		30094, -- Respiratory Rate
		10739818, -- SpO2 percent
		30100, -- Temperature
		119822492, -- Temperature Tympanic
		119822505, -- Temperature Rectal
		119822517, -- Temperature Axillary
		119822523, -- Temperature Intravascular
		119822536, -- Temperature Oral
		172563303, -- Temperature Skin
		172563306, -- Temperature Esophageal
		172563327, -- Temperature Brain
		263779626, -- Temperature Bladder		
		10679282 -- Temperature Sensor
	)
	AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
		CODE_DATES.START_DATETIME - (1 / 4)
		AND CODE_DATES.STOP_DATETIME + (1 / 2)
	AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'