WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS,
		ENCOUNTER.DISCH_DT_TM
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), PT_TEMPS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		MIN(CLINICAL_EVENT.EVENT_END_DT_TM) AS EVENT_END_DT_TM,
		MAX(CLINICAL_EVENT.EVENT_CD) KEEP (DENSE_RANK FIRST ORDER BY CLINICAL_EVENT.EVENT_END_DT_TM) AS EVENT_CD,
		MAX(CLINICAL_EVENT.RESUlT_VAL) KEEP (DENSE_RANK FIRST ORDER BY CLINICAL_EVENT.EVENT_END_DT_TM) AS RESULT_VAL,
		CLINICAL_EVENT.RESULT_UNITS_CD		
	FROM
		CLINICAL_EVENT,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			30100, -- Temperature
			119822492, -- Temperature Tympanic
			119822505, -- Temperature Rectal
			119822517, -- Temperature Axillary
			119822523, -- Temperature Intravascular
			119822536, -- Temperature Oral
			172563303, -- Temperature Skin
			172563306, -- Temperature Esophageal
			172563327, -- Temperature Brain
			263779626, -- Temperature Bladder		
			10679282 -- Temperature Sensor
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM < PATIENTS.DISCH_DT_TM
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'	
	GROUP BY
		PATIENTS.ENCNTR_ID,
		CLINICAL_EVENT.RESULT_UNITS_CD
), PT_MAPS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		MIN(CLINICAL_EVENT.EVENT_END_DT_TM) AS EVENT_END_DT_TM,
		MAX(CLINICAL_EVENT.EVENT_CD) KEEP (DENSE_RANK FIRST ORDER BY CLINICAL_EVENT.EVENT_END_DT_TM) AS EVENT_CD,
		MAX(CLINICAL_EVENT.RESUlT_VAL) KEEP (DENSE_RANK FIRST ORDER BY CLINICAL_EVENT.EVENT_END_DT_TM) AS RESULT_VAL,
		CLINICAL_EVENT.RESULT_UNITS_CD		
	FROM
		CLINICAL_EVENT,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			119822453, -- Mean Arterial Pressure
			173814326 -- Mean Arterial Pressure (Invasive)
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM < PATIENTS.DISCH_DT_TM
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'	
	GROUP BY
		PATIENTS.ENCNTR_ID,
		CLINICAL_EVENT.RESULT_UNITS_CD
), PT_HR AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		MIN(CLINICAL_EVENT.EVENT_END_DT_TM) AS EVENT_END_DT_TM,
		MAX(CLINICAL_EVENT.EVENT_CD) KEEP (DENSE_RANK FIRST ORDER BY CLINICAL_EVENT.EVENT_END_DT_TM) AS EVENT_CD,
		MAX(CLINICAL_EVENT.RESUlT_VAL) KEEP (DENSE_RANK FIRST ORDER BY CLINICAL_EVENT.EVENT_END_DT_TM) AS RESULT_VAL,
		CLINICAL_EVENT.RESULT_UNITS_CD		
	FROM
		CLINICAL_EVENT,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			30065, -- Peripheral Pulse Rate
			119822527 -- Apical Heart Rate
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM < PATIENTS.DISCH_DT_TM
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'	
	GROUP BY
		PATIENTS.ENCNTR_ID,
		CLINICAL_EVENT.RESULT_UNITS_CD
), PT_EVENTS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		MIN(CLINICAL_EVENT.EVENT_END_DT_TM) AS EVENT_END_DT_TM,
		CLINICAL_EVENT.EVENT_CD,
		MAX(CLINICAL_EVENT.RESUlT_VAL) KEEP (DENSE_RANK FIRST ORDER BY CLINICAL_EVENT.EVENT_END_DT_TM) AS RESULT_VAL,
		CLINICAL_EVENT.RESULT_UNITS_CD		
	FROM
		CLINICAL_EVENT,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			31806, -- Hct
			10662250, -- FIO2 (%)
			30094, -- Respiratory Rate
			53807854, -- POC A pH
			31090, -- Creatinine Lvl
			32170, -- Potassium Lvl
			32619, -- Sodium Lvl
			34402, -- WBC
			134422765 -- Glasgow Coma Score
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM < PATIENTS.DISCH_DT_TM
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'	
	GROUP BY
		PATIENTS.ENCNTR_ID,
		CLINICAL_EVENT.EVENT_CD,
		CLINICAL_EVENT.RESULT_UNITS_CD
), BASELINE_VALS AS (
	SELECT * FROM PT_TEMPS

	UNION

	SELECT * FROM PT_MAPS

	UNION

	SELECT * FROM PT_HR
	
	UNION
	
	SELECT * FROM PT_EVENTS
)

SELECT DISTINCT
	PATIENTS.ALIAS AS FIN,
	pi_from_gmt(BASELINE_VALS.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS EVENT_DATETIME,
	pi_get_cv_display(BASELINE_VALS.EVENT_CD) AS EVENT,
	BASELINE_VALS.RESULT_VAL AS EVENT_RESULT,
	pi_get_cv_display(BASELINE_VALS.RESULT_UNITS_CD) AS RESULT_UNITS
FROM
	BASELINE_VALS,
	PATIENTS
WHERE
	PATIENTS.ENCNTR_ID = BASELINE_VALS.ENCNTR_ID
